# Generated by Django 4.0.6 on 2022-07-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_alter_comments_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='writer',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
